#!/usr/bin/expect -f
set timeout 15
spawn ssh -o StrictHostKeyChecking=no it@192.168.9.9 "echo 'SSH Connection Successful'"
expect {
    "*password:" {
        send "Interst0ff\r"
        expect {
            "SSH Connection Successful" {
                send_user "SUCCESS\n"
                exit 0
            }
            default {
                send_user "FAILURE\n"
                exit 1
            }
        }
    }
    "SSH Connection Successful" {
        send_user "SUCCESS\n"
        exit 0
    }
    timeout {
        send_user "TIMEOUT\n"
        exit 2
    }
}
