/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated.security'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated.requests.$id'
import { Route as AuthenticatedNodesIdIndexRouteImport } from './routes/_authenticated.nodes.$id.index'
import { Route as AuthenticatedNodesIdSessionRouteImport } from './routes/_authenticated.nodes.$id.session'
import { Route as AuthenticatedNodesIdFilesRouteImport } from './routes/_authenticated.nodes.$id.files'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNodesIdIndexRoute =
  AuthenticatedNodesIdIndexRouteImport.update({
    id: '/nodes/$id/',
    path: '/nodes/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNodesIdSessionRoute =
  AuthenticatedNodesIdSessionRouteImport.update({
    id: '/nodes/$id/session',
    path: '/nodes/$id/session',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNodesIdFilesRoute =
  AuthenticatedNodesIdFilesRouteImport.update({
    id: '/nodes/$id/files',
    path: '/nodes/$id/files',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/nodes/$id/files': typeof AuthenticatedNodesIdFilesRoute
  '/nodes/$id/session': typeof AuthenticatedNodesIdSessionRoute
  '/nodes/$id/': typeof AuthenticatedNodesIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/nodes/$id/files': typeof AuthenticatedNodesIdFilesRoute
  '/nodes/$id/session': typeof AuthenticatedNodesIdSessionRoute
  '/nodes/$id': typeof AuthenticatedNodesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/nodes/$id/files': typeof AuthenticatedNodesIdFilesRoute
  '/_authenticated/nodes/$id/session': typeof AuthenticatedNodesIdSessionRoute
  '/_authenticated/nodes/$id/': typeof AuthenticatedNodesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/security'
    | '/settings'
    | '/requests/$id'
    | '/nodes/$id/files'
    | '/nodes/$id/session'
    | '/nodes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/admin'
    | '/security'
    | '/settings'
    | '/'
    | '/requests/$id'
    | '/nodes/$id/files'
    | '/nodes/$id/session'
    | '/nodes/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/requests/$id'
    | '/_authenticated/nodes/$id/files'
    | '/_authenticated/nodes/$id/session'
    | '/_authenticated/nodes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes/$id/': {
      id: '/_authenticated/nodes/$id/'
      path: '/nodes/$id'
      fullPath: '/nodes/$id/'
      preLoaderRoute: typeof AuthenticatedNodesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes/$id/session': {
      id: '/_authenticated/nodes/$id/session'
      path: '/nodes/$id/session'
      fullPath: '/nodes/$id/session'
      preLoaderRoute: typeof AuthenticatedNodesIdSessionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes/$id/files': {
      id: '/_authenticated/nodes/$id/files'
      path: '/nodes/$id/files'
      fullPath: '/nodes/$id/files'
      preLoaderRoute: typeof AuthenticatedNodesIdFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedNodesIdFilesRoute: typeof AuthenticatedNodesIdFilesRoute
  AuthenticatedNodesIdSessionRoute: typeof AuthenticatedNodesIdSessionRoute
  AuthenticatedNodesIdIndexRoute: typeof AuthenticatedNodesIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
  AuthenticatedNodesIdFilesRoute: AuthenticatedNodesIdFilesRoute,
  AuthenticatedNodesIdSessionRoute: AuthenticatedNodesIdSessionRoute,
  AuthenticatedNodesIdIndexRoute: AuthenticatedNodesIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
